const $ = (id)=>document.getElementById(id);
let imgObj=null, last=null;
const els=['photoInput','photoDrop','photoPreview','placeholder','cameraSelect','isoBase','apertureBase','fpsBase','priority'].reduce((a,id)=>(a[id]=$(id),a),{});
function init(){
  CAMERAS.forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=`${c.brand} ${c.model}`;els.cameraSelect.appendChild(o)});
  els.cameraSelect.value='red-helium'; updateCameraUI();
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active'); if(last) renderAll(last);});
  els.photoDrop.onclick=()=>els.photoInput.click(); els.photoInput.onchange=e=>{const f=e.target.files?.[0]; if(f) loadFile(f)};
  ['cameraSelect','isoBase','apertureBase','fpsBase','priority'].forEach(id=>els[id].onchange=()=>{if(id==='cameraSelect')updateCameraUI(); if(imgObj) analyze(imgObj);});
  $('resetBtn').onclick=()=>location.reload(); $('demoBtn').onclick=demo; $('saveBtn').onclick=saveSession;
}
function cam(){return CAMERAS.find(c=>c.id===els.cameraSelect.value)||CAMERAS[0]}
function updateCameraUI(){const c=cam(); els.isoBase.innerHTML=''; c.isoOptions.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;if(v===c.nativeISO)o.selected=true;els.isoBase.appendChild(o)}); $('cameraBadge').textContent=c.brand; $('camBrand').textContent=c.brand; $('camNotes').textContent=c.notes; $('camISO').textContent=c.secondNativeISO?`${c.nativeISO} / ${c.secondNativeISO}`:c.nativeISO; $('camColor').textContent=c.colorSpace; $('camGamma').textContent=c.gamma; $('codecOut').textContent=c.codecs[0]; $('gammaOut').textContent=c.gamma; $('spaceOut').textContent=c.colorSpace.split(' ')[0];}
function loadFile(file){const url=URL.createObjectURL(file); const im=new Image(); im.onload=()=>{imgObj=im; els.photoPreview.src=url; els.photoPreview.style.display='block'; els.placeholder.style.display='none'; analyze(im);}; im.onerror=()=>alert('No pude leer esa imagen. Prueba JPG o PNG.'); im.src=url;}
function demo(){const c=document.createElement('canvas');c.width=1200;c.height=800;const g=c.getContext('2d');let grd=g.createLinearGradient(0,0,0,800);grd.addColorStop(0,'#8fd4ff');grd.addColorStop(.5,'#ffc477');grd.addColorStop(1,'#101808');g.fillStyle=grd;g.fillRect(0,0,1200,800);g.fillStyle='#fff8';g.beginPath();g.arc(900,145,85,0,7);g.fill();g.fillStyle='#26303a';for(let i=0;i<16;i++){let h=120+Math.random()*260;g.fillRect(40+i*72,620-h,45,h)}g.fillStyle='#0c1108';g.fillRect(0,610,1200,190);const im=new Image();im.onload=()=>{imgObj=im;els.photoPreview.src=c.toDataURL();els.photoPreview.style.display='block';els.placeholder.style.display='none';analyze(im)};im.src=c.toDataURL();}
function analyze(im){const c=$('workCanvas'),w=640,h=Math.max(1,Math.round(im.height/im.width*w));c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(im,0,0,w,h);const data=ctx.getImageData(0,0,w,h);const d=data.data;let lumas=[],satSum=0,warm=0,cool=0;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2];let y=.2126*r+.7152*g+.0722*b;lumas.push(y);let max=Math.max(r,g,b),min=Math.min(r,g,b);satSum+=(max-min)/(max||1)*100;warm+=r-b;cool+=b-r;}lumas.sort((a,b)=>a-b);const avg=lumas.reduce((a,b)=>a+b,0)/lumas.length,p10=pct(lumas,.1),p50=pct(lumas,.5),p95=pct(lumas,.95),contrast=p95-p10,sat=satSum/(d.length/4);const scene=classify(avg,p95,p10,sat,warm,cool);const rec=recommend({avg,p10,p50,p95,contrast,sat,scene});last={canvas:c,data,avg,p10,p50,p95,contrast,sat,scene,rec};updateText(last);renderAll(last);}
function pct(a,p){return a[Math.min(a.length-1,Math.max(0,Math.floor(a.length*p)))]}
function classify(avg,p95,p10,sat,warm,cool){if(avg<45)return{label:'Noche / baja luz',icon:'☾',conf:88,note:'Escena oscura. Evita ND y abre lente.'}; if(p95>230&&avg>145)return{label:'Exterior soleado',icon:'☀',conf:92,note:'Altas luces fuertes. Prioriza ND y highlights.'}; if(avg>115&&cool>warm)return{label:'Exterior / sombra',icon:'◒',conf:78,note:'Luz suave o sombra abierta.'}; if(warm>cool&&sat>20&&avg>80)return{label:'Atardecer / interior cálido',icon:'◉',conf:75,note:'Dominante cálida. Ajusta WB según intención.'}; return{label:'Interior / luz controlada',icon:'◐',conf:72,note:'Exposición media. Revisa piel y sombras.'};}
function recommend(o){const c=cam();let iso=Number(els.isoBase.value)||c.nativeISO,ap=els.apertureBase.value,fps=Number(els.fpsBase.value)||24,shutter=`1/${Math.round(fps*2)}`,wb=c.wbDay,wbLabel='día/exterior',stops=0,nd='Sin ND',note='Puedes trabajar sin ND.',visual='Suave'; if(o.scene.label.includes('Noche')){iso=c.secondNativeISO||Math.min(3200,iso*2);wb=c.wbTungsten;wbLabel='baja luz';note='No uses ND. Abre apertura o añade luz.';visual='Levanta sombras';}
else if(o.p95>235||o.avg>180){stops=9;nd='ND 1.8 + ND 0.9';note='Mucha luz: usa ambos ND para mantener ISO y apertura.';visual='Reduce altas luces';}
else if(o.p95>218||o.avg>145){stops=6;nd='ND 1.8';note='Luz fuerte: ND 1.8 mantiene la apertura abierta.';visual='Protege highlights';}
else if(o.p95>195||o.avg>115){stops=3;nd='ND 0.9';note='Luz moderada: ND 0.9 ayuda sin cerrar lente.';visual='Control moderado';}
if(o.scene.label.includes('cálido')){wb=4000;wbLabel='cálido'} if(o.scene.label.includes('Interior')){wb=4300;wbLabel='interior'}
return{iso,ap,shutter,wb,wbLabel,stops,nd,note,visual,codec:c.codecs[0],gamma:c.gamma,space:c.colorSpace};}
function updateText(o){const r=o.rec;$('sceneIcon').textContent=o.scene.icon;$('sceneOut').textContent=o.scene.label;$('sceneNote').textContent=o.scene.note;$('confidenceOut').textContent=o.scene.conf+'%';$('isoOut').textContent=r.iso;$('apertureOut').textContent=r.ap;$('shutterOut').textContent=r.shutter;$('wbOut').textContent=r.wb+'K';$('wbLabel').textContent=r.wbLabel;$('codecOut').textContent=r.codec;$('gammaOut').textContent=r.gamma;$('spaceOut').textContent=r.space.split(' ')[0];$('ndOut').textContent=r.nd;$('stopsOut').textContent=r.stops+' pasos';$('ndNote').textContent=r.note;$('ndA').textContent=r.stops===9?'1.8':r.stops===6?'1.8':r.stops===3?'0.9':'—';$('ndB').textContent=r.stops===9?'0.9':'—';$('adjustBadge').textContent=r.nd;$('visualOut').textContent=r.visual;$('targetOut').textContent=els.priority.options[els.priority.selectedIndex].text;$('tipOut').textContent=`${cam().brand} ${cam().model}: ${r.note} ${cam().notes}`;$('mBright').textContent=Math.round(o.avg/2.55)+' IRE';$('mContrast').textContent=o.contrast>130?'Alto':o.contrast>80?'Medio':'Bajo';$('mHigh').textContent=Math.round(o.p95/2.55)+' IRE';$('mShadow').textContent=Math.round(o.p10/2.55)+' IRE';}
function renderAll(o){drawCompare(o);drawFalse(o);drawWave(o);drawHist(o)}
function size(c,w,h){c.width=w;c.height=h}
function drawCompare(o){['originalCanvas','adjustedCanvas'].forEach((id,idx)=>{const c=$(id);size(c,o.canvas.width,o.canvas.height);const x=c.getContext('2d');x.drawImage(o.canvas,0,0);if(idx){let im=x.getImageData(0,0,c.width,c.height),d=im.data,fac=o.rec.stops>=6?.78:o.rec.stops===3?.9:o.avg<55?1.18:1.02;for(let i=0;i<d.length;i+=4){d[i]=tone(d[i],fac);d[i+1]=tone(d[i+1],fac);d[i+2]=tone(d[i+2],fac)}x.putImageData(im,0,0)}})}
function tone(v,f){v=v*f;return Math.max(0,Math.min(255,255*(1-Math.exp(-v/235))))}
function drawFalse(o){const c=$('falseColorCanvas');size(c,o.data.width,o.data.height);const x=c.getContext('2d');const im=new ImageData(new Uint8ClampedArray(o.data.data),o.data.width,o.data.height),d=im.data;for(let i=0;i<d.length;i+=4){let y=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/2.55,col=falseCol(y);d[i]=col[0];d[i+1]=col[1];d[i+2]=col[2]}x.putImageData(im,0,0)}
function falseCol(ire){if(ire<10)return[88,30,180];if(ire<30)return[0,90,230];if(ire<50)return[30,195,70];if(ire<70)return[240,215,40];if(ire<90)return[255,120,15];return[230,30,40]}
function drawWave(o){const c=$('waveformCanvas');size(c,360,190);const x=c.getContext('2d');x.fillStyle='#050505';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#333';for(let y=20;y<c.height;y+=38){x.beginPath();x.moveTo(0,y);x.lineTo(c.width,y);x.stroke()}x.fillStyle='rgba(255,255,255,.08)';const d=o.data.data,w=o.data.width,h=o.data.height;for(let yy=0;yy<h;yy+=2){for(let xx=0;xx<w;xx+=2){let i=(yy*w+xx)*4,l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255;x.fillRect(xx/w*c.width,c.height-l*c.height,1,1)}}x.strokeStyle='#ff7900';x.beginPath();x.moveTo(0,c.height*.5);x.lineTo(c.width,c.height*.5);x.stroke()}
function drawHist(o){const c=$('histCanvas');size(c,360,190);const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);let bins=new Array(100).fill(0),d=o.data.data;for(let i=0;i<d.length;i+=4){let y=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/2.55;bins[Math.min(99,Math.floor(y))]++}let max=Math.max(...bins);x.fillStyle='#ddd';bins.forEach((v,i)=>{let h=v/max*(c.height-18);x.fillRect(i*c.width/100,c.height-h,Math.ceil(c.width/100),h)});x.fillStyle='#ff7900';x.fillRect(0,c.height-8,c.width,3)}
function saveSession(){if(!last)return alert('Sube una foto primero.');let arr=JSON.parse(localStorage.unojoSessions||'[]');arr.unshift({date:new Date().toLocaleString(),camera:cam().model,scene:last.scene.label,iso:last.rec.iso,nd:last.rec.nd,wb:last.rec.wb});localStorage.unojoSessions=JSON.stringify(arr.slice(0,30));alert('Sesión guardada en este navegador.');}
init();
